---
- name: Make linux user-friendly.
  hosts: all
  vars:
    the_user: "{{ ansible_user_id }}"

  tasks:
  - name: Install zsh.
    yum: 
      name: zsh
      state: latest
    become: true
 
  - name: Make zsh default.
    become: yes
    user:
      name: "{{ the_user }}"
      shell: /bin/zsh
 
  - name: Clone oh-my-zsh.
    git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: ~/.oh-my-zsh
 
  - name: Download configs.
    git:
      repo: https://github.com/AA122AA/initial_config
      dest: ~/initial_config
      clone: true
      update: true
 
  - name: Copy config.
    copy:
      remote_src: true
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: centos
      group: centos
      mode: 0644
    with_items:
      - src: /home/centos/initial_config/vimrc
        dest: /home/centos/.vimrc
      - src: /home/centos/initial_config/zshrc
        dest: /home/centos/.zshrc
 
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Register vim version
    debug:
      var: ansible_facts.packages['vim-common'][0]['version'][:1]
    register: vimVersion

  - name: Install development tools
    yum:
      name: "@Development Tools"
    become: yes
    when: vimVersion | int < 8

  - name: Install ncurses
    yum:
      name: ncurses-devel
    become: yes
    when: vimVersion | int < 8

  - name: Clone vim
    git:
      repo: https://github.com/vim/vim.git
      dest: ~/vim
    when: vimVersion | int < 8

      #  - name: Config for vim
      #    shell:
      #     cmd: ./configure --with-features=huge --enable-multibyte --enable-rubyinterp --enable-pythoninterp --enable-perlinterp --enable-luainterp
      #     chdir: ~/vim/src

       #   - name: Make distclean. 
       #    make:
       #      chdir: ~/vim/src
       #      target: distclean
       #    when: vimVersion | int < 8
    
  - name: Make vim. 
    make:
      chdir: ~/vim/src
    when: vimVersion | int < 8

  - name: Run make install vim
    command: make install 
      chdir: ~/vim/src
    become: yes
    when: vimVersion | int < 8

      # Не работает make install надо разобрать почему 

  - name: Remove old vim
    yum:
      name: 'vim*'
      state: remove
    become: yes
    when: vimVersion | int < 8



