---
- name: Make linux user-friendly.
  hosts: all
  vars:
    the_user: "{{ ansible_user_id }}"

  tasks:
  - name: Install zsh.
    ansible.builtin.package:
      name: zsh
      state: latest
    become: true
 
  - name: Make zsh default.
    become: yes
    user:
      name: "{{ the_user }}"
      shell: /bin/zsh
 
  - name: Clone oh-my-zsh.
    git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: ~/.oh-my-zsh

  - name: install autosuggestions
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions 
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
 
  - name: install powerfonts
    ansible.builtin.package:
      name: fonts-powerline
      state: latest
    become: true

  - name: Download configs.
    git:
      repo: https://github.com/AA122AA/initial_config
      dest: ~/initial_config
      clone: true
      update: true
 
  - name: Copy config.
    copy:
      remote_src: true
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: 0644
    with_items:
      - src: ~/initial_config/vimrc
        dest: ~/.vimrc
      - src: ~/initial_config/zshrc
        dest: ~/.zshrc
 
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto


